from sqlalchemy import Column, String, Integer, ForeignKey, Boolean, DateTime, Float, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.db.base import Base

class Assessment(Base):
    __tablename__ = "assessments"
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String)
    class_id = Column(Integer, ForeignKey("classes.id"))
    subject = Column(String)
    max_score = Column(Float)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

class AssessmentResult(Base):
    __tablename__ = "assessment_results"
    id = Column(Integer, primary_key=True, index=True)
    assessment_id = Column(Integer, ForeignKey("assessments.id"))
    student_id = Column(Integer, ForeignKey("users.id"))
    score = Column(Float)
    ai_feedback = Column(String, nullable=True) # Feedback generated by DokGuru
    created_at = Column(DateTime(timezone=True), server_default=func.now())
