from sqlalchemy import Column, String, Integer, ForeignKey, DateTime, Float, Date
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.db.base import Base

class Assessment(Base):
    __tablename__ = "assessments"
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=False)
    assessment_type = Column(String, nullable=False)  # QUIZ, EXAM, ASSIGNMENT, TEST
    class_id = Column(Integer, ForeignKey("classes.id", ondelete="CASCADE"), nullable=False)
    subject_id = Column(Integer, ForeignKey("subjects.id", ondelete="SET NULL"), nullable=True)
    created_by = Column(String, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    max_score = Column(Float, nullable=False, default=100.0)
    scheduled_date = Column(Date, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    classroom = relationship("ClassRoom")
    subject = relationship("Subject")
    teacher = relationship("User")
    results = relationship("AssessmentResult", back_populates="assessment", cascade="all, delete-orphan")

class AssessmentResult(Base):
    __tablename__ = "assessment_results"
    id = Column(Integer, primary_key=True, index=True)
    assessment_id = Column(Integer, ForeignKey("assessments.id", ondelete="CASCADE"), nullable=False)
    student_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    score = Column(Float, nullable=False)
    ai_feedback = Column(String, nullable=True)  # Feedback generated by DokGuru
    submitted_by = Column(String, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)  # Teacher who entered marks
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    assessment = relationship("Assessment", back_populates="results")
    student = relationship("User", foreign_keys=[student_id])
    grader = relationship("User", foreign_keys=[submitted_by])
